/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OurMissionRouteImport } from './routes/our-mission'
import { Route as LogoPreviewRouteImport } from './routes/logo-preview'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CausesRouteImport } from './routes/causes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonateThankYouRouteImport } from './routes/donate.thank-you'
import { Route as DonateSuccessRouteImport } from './routes/donate.success'
import { Route as DonateFailureRouteImport } from './routes/donate.failure'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OurMissionRoute = OurMissionRouteImport.update({
  id: '/our-mission',
  path: '/our-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoPreviewRoute = LogoPreviewRouteImport.update({
  id: '/logo-preview',
  path: '/logo-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CausesRoute = CausesRouteImport.update({
  id: '/causes',
  path: '/causes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateThankYouRoute = DonateThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => DonateRoute,
} as any)
const DonateSuccessRoute = DonateSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => DonateRoute,
} as any)
const DonateFailureRoute = DonateFailureRouteImport.update({
  id: '/failure',
  path: '/failure',
  getParentRoute: () => DonateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/causes': typeof CausesRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRouteWithChildren
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/logo-preview': typeof LogoPreviewRoute
  '/our-mission': typeof OurMissionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/donate/failure': typeof DonateFailureRoute
  '/donate/success': typeof DonateSuccessRoute
  '/donate/thank-you': typeof DonateThankYouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/causes': typeof CausesRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRouteWithChildren
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/logo-preview': typeof LogoPreviewRoute
  '/our-mission': typeof OurMissionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/donate/failure': typeof DonateFailureRoute
  '/donate/success': typeof DonateSuccessRoute
  '/donate/thank-you': typeof DonateThankYouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/causes': typeof CausesRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRouteWithChildren
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/logo-preview': typeof LogoPreviewRoute
  '/our-mission': typeof OurMissionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/donate/failure': typeof DonateFailureRoute
  '/donate/success': typeof DonateSuccessRoute
  '/donate/thank-you': typeof DonateThankYouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/causes'
    | '/contact'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/logo-preview'
    | '/our-mission'
    | '/sitemap.xml'
    | '/volunteer'
    | '/donate/failure'
    | '/donate/success'
    | '/donate/thank-you'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/causes'
    | '/contact'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/logo-preview'
    | '/our-mission'
    | '/sitemap.xml'
    | '/volunteer'
    | '/donate/failure'
    | '/donate/success'
    | '/donate/thank-you'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/causes'
    | '/contact'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/logo-preview'
    | '/our-mission'
    | '/sitemap.xml'
    | '/volunteer'
    | '/donate/failure'
    | '/donate/success'
    | '/donate/thank-you'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CausesRoute: typeof CausesRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRouteWithChildren
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  LogoPreviewRoute: typeof LogoPreviewRoute
  OurMissionRoute: typeof OurMissionRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-mission': {
      id: '/our-mission'
      path: '/our-mission'
      fullPath: '/our-mission'
      preLoaderRoute: typeof OurMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-preview': {
      id: '/logo-preview'
      path: '/logo-preview'
      fullPath: '/logo-preview'
      preLoaderRoute: typeof LogoPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causes': {
      id: '/causes'
      path: '/causes'
      fullPath: '/causes'
      preLoaderRoute: typeof CausesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/thank-you': {
      id: '/donate/thank-you'
      path: '/thank-you'
      fullPath: '/donate/thank-you'
      preLoaderRoute: typeof DonateThankYouRouteImport
      parentRoute: typeof DonateRoute
    }
    '/donate/success': {
      id: '/donate/success'
      path: '/success'
      fullPath: '/donate/success'
      preLoaderRoute: typeof DonateSuccessRouteImport
      parentRoute: typeof DonateRoute
    }
    '/donate/failure': {
      id: '/donate/failure'
      path: '/failure'
      fullPath: '/donate/failure'
      preLoaderRoute: typeof DonateFailureRouteImport
      parentRoute: typeof DonateRoute
    }
  }
}

interface DonateRouteChildren {
  DonateFailureRoute: typeof DonateFailureRoute
  DonateSuccessRoute: typeof DonateSuccessRoute
  DonateThankYouRoute: typeof DonateThankYouRoute
}

const DonateRouteChildren: DonateRouteChildren = {
  DonateFailureRoute: DonateFailureRoute,
  DonateSuccessRoute: DonateSuccessRoute,
  DonateThankYouRoute: DonateThankYouRoute,
}

const DonateRouteWithChildren =
  DonateRoute._addFileChildren(DonateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CausesRoute: CausesRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRouteWithChildren,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  LogoPreviewRoute: LogoPreviewRoute,
  OurMissionRoute: OurMissionRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
